- .github/workflows/main.yml
- .github/workflows/pr.yml
Use a reusable workflow to build the poetry project and upload coverage to Codecov to reduce code duplication.
> ci: use reusable workflow to build poetry project

- .github/workflows/publish_stdlib_to_pypi.yml
Use reusable workflow to publish project to PyPI.
> ci: use reusable workflow to publish project to PyPI

- docs/README.md
- docs/tutorials/README.md
- mkdocs.yml
The homepage of the documentation was linking to documentation of the DSL. These links are now removed. We'll add more content to the homepage in a later PR.
> docs: remove outdated information from homepage of documentation

- .github/workflows/merge_queue.yml
Our concurrency configuration for PRs does not work for merge queues since the `head_ref` is always blank, leading to incorrectly cancelled jobs. This PR, therefore, adds another workflow for the merge queue without concurrency.
> ci: split PR and merge queue workflows

- .github/workflows/merge_queue.yml
- .github/workflows/pr.yml
* No longer compute test coverage in the merge queue workflow, which should speed it up slightly.
> ci: don't compute test coverage in merge queue workflow

- .github/workflows/main.yml
- .github/workflows/pr.yml
Remove explicit `CODECOV_TOKEN`, since it's not needed for public repos.
> ci: remove CODECOV_TOKEN

- docs/README.md
- mkdocs.yml
- src/README.md
The term "stdlib" makes sense from the perspective of the entire project. For someone who just wants to use the Python components, however, we should instead talk about the "Safe-DS Python Library".
> docs: better headings

- mkdocs.yml
Use default symbol for permalinks since changing them doesn't work in notebooks. This gives us a consistent look at least.
> docs: use default symbol for permalinks

- docs/README.md
Closes #19.
See the issue for more details.
> docs: improve README

- .github/workflows/main.yml
- .github/workflows/pr.yml
We support Python 3.11, so we should also ensure the library can be used with it.
> ci: also build with Python 3.11

- src/safeds/ml/classification/_ada_boost.py
- src/safeds/ml/classification/_classifier.py
- src/safeds/ml/classification/_decision_tree.py
- src/safeds/ml/classification/_gradient_boosting_classification.py
- src/safeds/ml/classification/_k_nearest_neighbors.py
- src/safeds/ml/classification/_logistic_regression.py
- src/safeds/ml/classification/_random_forest.py
- src/safeds/ml/regression/_ada_boost.py
- src/safeds/ml/regression/_decision_tree.py
- src/safeds/ml/regression/_elastic_net_regression.py
- src/safeds/ml/regression/_gradient_boosting_regression.py
- src/safeds/ml/regression/_k_nearest_neighbors.py
- src/safeds/ml/regression/_lasso_regression.py
- src/safeds/ml/regression/_linear_regression.py
- src/safeds/ml/regression/_random_forest.py
- src/safeds/ml/regression/_regressor.py
- src/safeds/ml/regression/_ridge_regression.py
This can also be accomplished by renaming columns in the returned table. If the input table already contains the column we want to predict, it's an indicator for #9, so we shouldn't just let people change the name here.
> feat: remove `target_name` parameter of `predict`

- src/safeds/ml/_util_sklearn.py
- src/safeds/ml/classification/_ada_boost.py
- src/safeds/ml/classification/_classifier.py
- src/safeds/ml/classification/_decision_tree.py
- src/safeds/ml/classification/_gradient_boosting_classification.py
- src/safeds/ml/classification/_k_nearest_neighbors.py
- src/safeds/ml/classification/_logistic_regression.py
- src/safeds/ml/classification/_random_forest.py
- src/safeds/ml/regression/_ada_boost.py
- src/safeds/ml/regression/_decision_tree.py
- src/safeds/ml/regression/_elastic_net_regression.py
- src/safeds/ml/regression/_gradient_boosting_regression.py
- src/safeds/ml/regression/_k_nearest_neighbors.py
- src/safeds/ml/regression/_lasso_regression.py
- src/safeds/ml/regression/_linear_regression.py
- src/safeds/ml/regression/_random_forest.py
- src/safeds/ml/regression/_regressor.py
- src/safeds/ml/regression/_ridge_regression.py
The `predict` method returns the original feature vector combined with the predicted target values. This is exactly what a `TaggedTable` can express, so we return this instead of a `Table`.
> feat: return `TaggedTable` from `predict`

- src/safeds/data/tabular/containers/_column.py
- tests/safeds/data/tabular/containers/_column/test_rename.py
New method on `Column` that returns a new column with a new name.
> feat: change the name of a `Column`

- src/safeds/data/tabular/containers/_column.py
- src/safeds/data/tabular/containers/_table.py
Closes #78.
For the sake of consistency it is now possible to pass the type of a `Column` in the constructor. This also improves performance, for example when we call `get_column` on a `Table`. In that case we already know the type of the column anyway, so there's no reason to infer it again.
> feat: optionally pass type to column

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_correlation_heatmap.py
Closes #89.
We no longer raise an exception when `correlation_heatmap` is called on a table with some non-numerical columns. Instead, we simply don't show these columns in the created plot.
> feat: allow calling `correlation_heatmap` with non-numerical columns

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_drop_rows_with_outliers.py
Closes #93.
Rename `remove_outliers` to `drop_rows_with_outliers` in `Table`.
> feat: rename `remove_outliers` to `drop_rows_with_outliers`

- docs/tutorials/data_processing.ipynb
- src/safeds/data/tabular/containers/_table.py
- src/safeds/data/tabular/transformation/_label_encoder.py
- src/safeds/data/tabular/transformation/_one_hot_encoder.py
- tests/safeds/data/tabular/containers/_table/test_keep_only_columns.py
In `Table`, rename `keep_columns` to `keep_only_columns` to better match the semantics of the method.
> feat: rename `keep_columns` to `keep_only_columns`

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_sort_rows.py
Closes #14.
* Add a new method `sort_rows` to the `Table` class to sort rows using some criteria.
* Rename the parameter of `sort_columns` for the sorting criteria to `comparator`.
> feat: `sort_rows` of a `Table`

- src/safeds/data/tabular/containers/_column.py
- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_column/test_column.py
- tests/safeds/data/tabular/containers/_column/test_column_properties.py
- tests/safeds/data/tabular/containers/_column/test_correlation_with.py
- tests/safeds/data/tabular/containers/_column/test_count.py
- tests/safeds/data/tabular/containers/_column/test_get_unique_values.py
- tests/safeds/data/tabular/containers/_column/test_get_value.py
- tests/safeds/data/tabular/containers/_column/test_getitem.py
- tests/safeds/data/tabular/containers/_column/test_has_missing_values.py
- tests/safeds/data/tabular/containers/_column/test_idness.py
- tests/safeds/data/tabular/containers/_column/test_iter.py
- tests/safeds/data/tabular/containers/_column/test_len.py
- tests/safeds/data/tabular/containers/_column/test_missing_value_ratio.py
- tests/safeds/data/tabular/containers/_column/test_rename.py
- tests/safeds/data/tabular/containers/_column/test_stability.py
- tests/safeds/data/tabular/containers/_column/test_sum.py
- tests/safeds/data/tabular/containers/_table/test_add_column.py
- tests/safeds/data/tabular/containers/_table/test_add_columns.py
- tests/safeds/data/tabular/containers/_table/test_from_columns.py
- tests/safeds/data/tabular/containers/_table/test_replace_column.py
- tests/safeds/data/tabular/containers/_table/test_sort_columns.py
- tests/safeds/data/tabular/containers/_table/test_sort_rows.py
- tests/safeds/data/tabular/containers/_table/test_table_add_column.py
- tests/safeds/data/tabular/containers/_table/test_to_columns.py
- tests/safeds/ml/classification/test_classifier.py
- tests/safeds/ml/regression/test_regressor.py
The order of parameters of the `__init__` method of `Column` is now
1. `name` (was 2.)
2. `data` (was 1.)
3. `type_`.
Having the `name` first is more readable since the data can be quite long and highlights that the `name` acts as a key and the `data` as a value.
> feat: swap `name` and `data` parameters of `Column`

- tests/safeds/ml/classification/test_ada_boost.py
- tests/safeds/ml/classification/test_classifier.py
- tests/safeds/ml/classification/test_decision_tree.py
- tests/safeds/ml/classification/test_gradient_boosting.py
- tests/safeds/ml/classification/test_k_nearest_neighbors.py
- tests/safeds/ml/classification/test_logistic_regression.py
- tests/safeds/ml/classification/test_random_forest.py
- tests/safeds/ml/regression/test_ada_boost.py
- tests/safeds/ml/regression/test_decision_tree.py
- tests/safeds/ml/regression/test_elastic_net.py
- tests/safeds/ml/regression/test_gradient_boosting.py
- tests/safeds/ml/regression/test_k_nearest_neighbors.py
- tests/safeds/ml/regression/test_lasso_regression.py
- tests/safeds/ml/regression/test_linear_regression.py
- tests/safeds/ml/regression/test_random_forest.py
- tests/safeds/ml/regression/test_regressor.py
- tests/safeds/ml/regression/test_ridge_regression.py
Closes #102.
Instead of simply checking that the `predict` method of models does not raise an exception, we now also check that
* the features of the input are preserved in the result
* the target column has the correct name.
> test: better tests for `predict` method of models

- src/safeds/data/tabular/transformation/_table_transformer.py
- tests/safeds/data/tabular/transformation/test_imputer.py
- tests/safeds/data/tabular/transformation/test_label_encoder.py
- tests/safeds/data/tabular/transformation/test_one_hot_encoder.py
Closes #112.
Rename `fit_transform` to `fit_and_transform` to better indicate that this method combines the two steps `fit` and `transform`.
> feat: rename `fit_transform` to `fit_and_transform`

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_shuffle_rows.py
To be consistent with the other methods of `Table`, I've rename `shuffle` to `shuffle_rows`. This makes it obvious that the columns are not changed.
> feat: rename `shuffle` to `shuffle_rows`

- docs/tutorials/data_processing.ipynb
- docs/tutorials/data_visualization.ipynb
- docs/tutorials/machine_learning.ipynb
- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_slice_rows.py
To be consistent with the other methods of `Table`, I've rename `slice` to `slice_rows`. This makes it obvious that the columns are not changed.
> feat: rename `slice` to `slice_rows`

- src/safeds/data/tabular/transformation/__init__.py
`TableTransformer` and `InvertibleTableTransformer` are now included in the correct `__init__` file, so they show up in the documentation.
> fix: export `TableTransformer` and `InvertibleTableTransformer`

- src/safeds/data/tabular/transformation/__init__.py
- src/safeds/data/tabular/transformation/_imputer.py
- src/safeds/data/tabular/typing/__init__.py
- src/safeds/data/tabular/typing/_imputer_strategy.py
- tests/safeds/data/tabular/transformation/test_imputer.py
* Move the abstract base class `ImputerStrategy` to `safeds.data.tabular.typing` since it is only needed for type annotations
* Improve documentation
> feat: move `ImputerStrategy` to `safeds.data.tabular.typing`

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_from_columns.py
- tests/safeds/data/tabular/containers/_table/test_keep_only_columns.py
Closes #115 .
Fixed `table.keep_only_columns` to rearrange the column names correctly
Fixed grammar in two docs
> fix: `table.keep_only_columns` now maps column names to correct data

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/test_table.py
Closes #199.
* Add a method `__dataframe__` to `Table` to support the [dataframe interchange protocol](https://data-apis.org/dataframe-protocol/latest/index.html#).
> feat: dataframe interchange protocol

- src/safeds/data/tabular/transformation/_one_hot_encoder.py
- tests/safeds/data/tabular/transformation/test_one_hot_encoder.py
Closes #109.
`OneHotEncoder.inverse_transform` now maintains the column order from the original table (#109)
Fixed bug with `OneHotEncoder.inverse_transform` to not work if not all columns were fitted
New feature columns in `OneHotEncoder` will now be inserted where the combined columns were in the original table
> feat: `OneHotEncoder.inverse_transform` now maintains the column order from the original table

- src/safeds/data/tabular/containers/_row.py
- src/safeds/data/tabular/containers/_table.py
- src/safeds/data/tabular/transformation/_imputer.py
- src/safeds/data/tabular/transformation/_label_encoder.py
- tests/safeds/data/tabular/containers/_table/test_add_row.py
- tests/safeds/data/tabular/containers/_table/test_add_rows.py
- tests/safeds/data/tabular/containers/_table/test_summary.py
- tests/safeds/data/tabular/containers/test_row.py
Closes #202.
* Explicitly set the names of the columns in the `DataFrame` that is contained in a `Table`
> refactor: keep column names of `DataFrame` inside `Table`

- src/safeds/data/tabular/containers/_row.py
- tests/safeds/data/tabular/containers/test_row.py
- tests/safeds/data/tabular/containers/test_table.py
Closes #204.
Add two methods to `Row`:
* `from_dict` to create a `Row` from a `dict[str, Any]`
* `to_dict` to convert a `Row` to a `dict[str, Any]`
> feat: convert between `Row` and `dict`

- src/safeds/data/tabular/containers/_row.py
- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_add_row.py
- tests/safeds/data/tabular/containers/_table/test_add_rows.py
- tests/safeds/data/tabular/containers/_table/test_to_rows.py
- tests/safeds/data/tabular/containers/test_row.py
Closes partially #196.
Closes #149.
* `Row` now uses a `polars.DataFrame` instead of a `pandas.Series` to store its data. The `DataFrame` can directly store the column names.
* Remove the `__hash__` method. A `Row` can no longer be used in a `set` and as the key of a `dict`. If we find a use-case for this, we'll add it back.
> feat: back `Row` by a `polars.DataFrame`

- src/safeds/data/tabular/transformation/_imputer.py
- src/safeds/data/tabular/transformation/_label_encoder.py
- src/safeds/data/tabular/transformation/_one_hot_encoder.py
- src/safeds/data/tabular/transformation/_table_transformer.py
- tests/safeds/data/tabular/transformation/test_imputer.py
- tests/safeds/data/tabular/transformation/test_label_encoder.py
- tests/safeds/data/tabular/transformation/test_one_hot_encoder.py
Closes #179.
Every `fit` method of `TableTransformer`s now requires `column_names` to be explicitly set.
> feat: Set `column_names` in `fit` methods of table transformers to be required

- src/safeds/data/tabular/transformation/_label_encoder.py
- src/safeds/ml/classical/_util_sklearn.py
When we tried to test whether a specific warning was issued, we discovered that these tests failed if all tests were run but passed if only the test for the warning was run. This happened because one module basically disabled all warnings when it was loaded. This behavior is now removed and instead one specific warning is disabled for the one call that may create it.
> fix: selectively ignore one warning instead of all warnings

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_inverse_transform_table.py
- tests/safeds/data/tabular/transformation/test_one_hot_encoder.py
Closes #111.
Added method `Table.inverse_transform_table` which takes the fitted transformer and returns the original table
Co-authored-by: sibre28 <86068340+sibre28@users.noreply.github.com>
> feat: Added method `Table.inverse_transform_table` which returns the original table

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_inverse_transform_table.py
- tests/safeds/data/tabular/containers/_table/test_transform_table.py
Closes #110.
Added `Table.transform_table` Method which returns a Table transformed with the given `TableTransformer`
Co-authored-by: Marsmaennchen221 <47296670+Marsmaennchen221@users.noreply.github.com>
> feat: Added `Table.transform_table` method which returns the transformed Table

- src/safeds/data/tabular/containers/_column.py
- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/test_column.py
- tests/safeds/data/tabular/containers/test_row.py
- tests/safeds/data/tabular/containers/test_table.py
Use `_repr_html_` instead of `_ipython_display_` to display `Table`s and `Column`s in Jupyter notebooks.
> refactor: replace `_ipython_display_` methods with `_repr_html_`

- src/safeds/data/tabular/containers/_column.py
- src/safeds/data/tabular/containers/_row.py
- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/test_column.py
- tests/safeds/data/tabular/containers/test_row.py
- tests/safeds/data/tabular/containers/test_table.py
Closes #140.
Add method `to_html` to `Table`, `Column`, and `Row` that returns an HTML representation of the respective container.
> feat: convert containers for tabular data to HTML

- pyproject.toml
- src/safeds/data/tabular/typing/_schema.py
- tests/safeds/data/tabular/typing/test_schema.py
Closes #151.
* Add method `to_dict` to `Schema` to convert a `Schema` to a `dict`
* Nicely format `Schema` in Jupyter notebook
* Add examples to docstrings
> feat: convert `Schema` to `dict` and format it nicely in a notebook

- src/safeds/data/tabular/containers/_column.py
- src/safeds/data/tabular/containers/_row.py
- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_column/test_number_of_rows.py
- tests/safeds/data/tabular/containers/_table/test_add_column.py
- tests/safeds/data/tabular/containers/_table/test_add_columns.py
- tests/safeds/data/tabular/containers/_table/test_add_row.py
- tests/safeds/data/tabular/containers/_table/test_add_rows.py
- tests/safeds/data/tabular/containers/_table/test_filter_rows.py
- tests/safeds/data/tabular/containers/_table/test_number_of_columns.py
- tests/safeds/data/tabular/containers/_table/test_number_of_rows.py
- tests/safeds/data/tabular/containers/_table/test_remove_rows_with_missing_values.py
- tests/safeds/data/tabular/containers/_table/test_remove_rows_with_outliers.py
- tests/safeds/data/tabular/containers/_table/test_rename.py
- tests/safeds/data/tabular/containers/_table/test_sort_columns.py
- tests/safeds/data/tabular/containers/_table/test_table.py
- tests/safeds/data/tabular/containers/test_row.py
* Rename `n_columns` to `number_of_columns`
* Rename `n_rows` to `number_of_rows`
Reason: The prefix `n` is commonly used instead of `number_of`. However, we also need to add a parameter to `AdaBoost` to set the maximum number of learners (#171). Calling that `maximum_n_learners` doesn't look nearly as readable to me as `maximum_number_of_learners`. And if we don't use `n` to replace `number_of` here, we shouldn't use this anywhere.
> feat: replace prefix `n` with `number_of`

- src/safeds/ml/classical/classification/_ada_boost.py
- src/safeds/ml/classical/regression/_ada_boost.py
- tests/safeds/ml/classical/classification/test_ada_boost.py
- tests/safeds/ml/classical/regression/test_ada_boost.py
Closes #167.
Adds learning_rate parameter to AdaBoost classifier and regressor.
> feat: add `learning_rate` to AdaBoost classifier and regressor.

- src/safeds/ml/classical/classification/_gradient_boosting_classification.py
- src/safeds/ml/classical/regression/_gradient_boosting_regression.py
- tests/safeds/ml/classical/classification/test_gradient_boosting_classification.py
- tests/safeds/ml/classical/regression/test_gradient_boosting_regression.py
Closes #168.
Add `learning_rate` parameter to `GradientBoosting` classifier and regressor.
> feat: set learning rate of Gradient Boosting models

- src/safeds/data/tabular/containers/_column.py
- src/safeds/data/tabular/containers/_row.py
- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_from_pandas_dataframe.py
- tests/safeds/data/tabular/containers/test_row.py
Add method `_from_pandas_dataframe` to create a `Table` from a `pandas.DataFrame`. This can be called internally instead of the constructor (once #256 is done), so we can provide a usable constructor.
> refactor: create `Table` from `pandas.DataFrame`

- docs/CHANGELOG.md
- src/safeds/data/tabular/containers/_table.py
- src/safeds/data/tabular/transformation/_imputer.py
- src/safeds/data/tabular/transformation/_label_encoder.py
- src/safeds/data/tabular/transformation/_one_hot_encoder.py
- src/safeds/data/tabular/transformation/_table_transformer.py
Closes #189.
Highlighting the fact, that fitting methods of Classifier, Regressor, Tabletransformer and certain methods of the _table class do not work in place.
> docs: Highlighting the fact, that certain methods do not work in place

- docs/development/guidelines.md
- src/safeds/ml/classical/classification/_ada_boost.py
- src/safeds/ml/classical/classification/_gradient_boosting.py
- src/safeds/ml/classical/classification/_random_forest.py
- src/safeds/ml/classical/classification/_support_vector_machine.py
- src/safeds/ml/classical/regression/_ada_boost.py
- src/safeds/ml/classical/regression/_elastic_net_regression.py
- src/safeds/ml/classical/regression/_gradient_boosting.py
- src/safeds/ml/classical/regression/_lasso_regression.py
- src/safeds/ml/classical/regression/_random_forest.py
- src/safeds/ml/classical/regression/_ridge_regression.py
- src/safeds/ml/classical/regression/_support_vector_machine.py
Closes #278.
* Mark optional hyperparameters as keyword-only
* Add guideline to consider marking optional parameters as keyword-only
> feat: mark optional hyperparameters as keyword only

- src/safeds/data/tabular/transformation/_one_hot_encoder.py
Closes #181.
Improve documentation of `OneHotEncoder`.
> docs: improve documentation for `OneHotEncoder`

- src/safeds/data/tabular/containers/_table.py
- src/safeds/data/tabular/containers/_tagged_table.py
- tests/safeds/data/tabular/containers/test_tagged_table.py
Closes #293.
Change constructor of `TaggedTable` to be more usable. The usual way to get a `TaggedTable` is still to call the `tag_column` method of `Table`.
> feat: usable constructor for `TaggedTable`

- tests/safeds/data/tabular/containers/_table/test_plot_boxplots.py
test: Correcting test for `Table.plot_boxplots` to not save the file the test uses to verify the result
> test: Correcting test for `Table.plot_boxplots` to not save the file the test uses to verify the result

- src/safeds/data/tabular/transformation/_imputer.py
- src/safeds/data/tabular/transformation/_label_encoder.py
- src/safeds/data/tabular/transformation/_one_hot_encoder.py
- src/safeds/data/tabular/transformation/_range_scaler.py
- tests/safeds/data/tabular/transformation/test_imputer.py
- tests/safeds/data/tabular/transformation/test_label_encoder.py
- tests/safeds/data/tabular/transformation/test_one_hot_encoder.py
- tests/safeds/data/tabular/transformation/test_range_scaler.py
Closes #323.
Removed the warnings from `get_names_of_added_columns`, `get_names_of_changed_columns` and `get_names_of_removed_columns` in all transformers.
Updated tests accordingly.
> feat: Remove warnings thrown in new `Transformer` methods

- src/safeds/ml/hyperparameters/__init__.py
- src/safeds/ml/hyperparameters/_choice.py
- tests/safeds/ml/hyperparameters/test_choice.py
Add a class to represent possible choices for the value of a hyperparameter. This is in preparation for #264.
> feat: add `Choice` class for possible values of hyperparameter

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_group_by.py
Closes #160.
Added a `group_by` method for the table class that requires a lambda function which computes the grouping keys. The method returns a dictionary with the computed keys as keys and the grouped rows as new Tables as values.
> feat: Added `Table.group_by` to group a table by a given key

- tests/safeds/data/tabular/containers/_table/test_replace_column.py
Closes #301.
Added a new testcase for `replace_column` to verify that the method can handle an empty list as argument.
> test: Add empty list testcase for `replace_column`

- src/safeds/data/image/containers/_image.py
* Remove default value of `radius` parameter of `Image.blur` to be in line with other methods.
> fix: remove default value of `radius` parameter of `blur`

- src/safeds/data/tabular/containers/_column.py
- tests/safeds/data/tabular/containers/_column/test_stability.py
Closes #319 
The docstring of the method clarifies that the stability is not defined if a column contains only null values.
The method raises a ValueError if the column contains only null values.
> feat: improve error handling of `column.stability` when given a column that contains only None

- tests/safeds/data/tabular/containers/_table/test_repr.py
Closes #349 
Added a test_repr.py file to `tests/safeds/data/tabular/containers/_table` that tests the fuction __repr__ of class Table
> feat: added test_repr table tests

- mkdocs.yml
Closes #423.
* The `Getting started` tutorial can now be found under `Tutorials` on the documentation webpage.
> docs: Add link to `Getting started` tutorial under `Tutorials` section on documentation webpage

- poetry.lock
- tests/safeds/data/tabular/transformation/test_imputer.py
- tests/safeds/data/tabular/transformation/test_one_hot_encoder.py
Closes #399.
* Ignore the `UserWarning` about data being already numerical thrown by `OneHotEncoder` in `nan` testcase.
* Ignore `UserWarning`s about multiple most common values existing thrown by `Imputer` in testcases that are not meant to test for warnings.
> test: Handle `UserWarning`s correctly in tests

- .github/workflows/main.yml
- .github/workflows/pr.yml
Compute coverage during the Python 3.11 run since it's slightly faster than the 3.10 run.
> ci: compute coverage during Python 3.11 run

- docs/README.md
Closes #441.
Fixed the broken link to our project guidelines in our README, which was a regression from #427.
> docs: Fix broken link in README.md

- mkdocs.yml
- src/safeds/data/image/containers/_image.py
- src/safeds/data/tabular/containers/_tagged_table.py
- src/safeds/data/tabular/transformation/_range_scaler.py
Closes #429
* Fix griffe warnings
* Enable strict mode of `mkdocs` to fail on warnings
> docs: fix griffe warnings

- docs/development/project_guidelines.md
- docs/tutorials/getting_started.ipynb
- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_group_rows_by.py
- tests/safeds/data/tabular/containers/_table/test_split_rows.py
- tests/safeds/data/tabular/containers/_table/test_summarize_statistics.py
Closes #439
* Rename `group_by` to `group_rows_by`
* Rename `split` to `split_rows`
* Rename `summary` to `summarize_statistics`
> feat: rename several `Table` methods for consistency

- src/safeds/data/tabular/transformation/_imputer.py
- tests/safeds/data/tabular/transformation/test_imputer.py
* Don't warn in `Imputer` if some columns of the `Table` passed to `transform` don't have missing values. The `Imputer` is used to guarantee that no missing values exist in a column. We should not need to check beforehand whether a column actually has missing values.
> fix: don't warn if `Imputer` transforms column without missing values

- .github/CODEOWNERS
- .github/workflows/issue.yml
- docs/CHANGELOG.md
- docs/README.md
- docs/development/project_guidelines.md
- docs/tutorials/data_visualization.ipynb
- mkdocs.yml
- package-lock.json
- package.json
- pyproject.toml
- tests/safeds/data/tabular/containers/_table/test_keep_only_columns.py
- tests/safeds/ml/classical/classification/test_classifier.py
- tests/safeds/ml/classical/regression/test_regressor.py
- tests/safeds/ml/classical/test_util_sklearn.py
* Rename repo to `Library` to emphasize that the library can also be used directly from Python and not just from the [DSL](https://github.com/Safe-DS/DSL).
> chore: rename repo

- .github/workflows/main.yml
- .github/workflows/pr.yml
- poetry.lock
- pyproject.toml
Closes #509
`torch` does not support Python 3.12 yet, so we need to restrict our supported Python version until it does.
> build: temporarily remove Python 3.12 support

- .github/workflows/main.yml
- .github/workflows/pr.yml
- poetry.lock
- pyproject.toml
Add Python 3.12 support
Update used cuda Version to 12.1
Update PyTorch to Version 2.2
Update TorchVision to Version 0.17
> build: Add Python 3.12 support

- src/safeds/data/tabular/transformation/_discretizer.py
Change the type of the `number_of_bins` parameter of `Discretizer.__init__` from `float` to `int`.
> fix: incorrect type hint for `number_of_bins` parameter

- src/safeds/data/image/containers/_image.py
Closes #583
Replace `Ìmage` with `Image` in docstring of `Image.flip_horizontally`.
> docs: fix typo in docstring of `Image.flip_horizontally`

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_add_rows.py
Fixes partially #575
Add special case to `add_rows` when adding a `Table`. 
The table is no longer split into a list of rows, instead it is directly added to the `DataFrame`.
In special cases, this may improve the performance up to 1000x.
> perf: treat Tables specially when calling add_rows

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_add_rows.py
See #606 
perf: Add special case to `Table.add_rows` to increase performance
> perf: Add special case to `Table.add_rows` to increase performance

- src/safeds/ml/nn/_forward_layer.py
- tests/safeds/ml/nn/test_forward_layer.py
Closes #633 
Added `__hash__`, `__eq__` and `__sizeof__` in `ForwardLayer`
> feat: Add hash,eq and sizeof in ForwardLayer

- src/safeds/data/tabular/containers/_row.py
- tests/safeds/data/tabular/containers/test_row.py
Closes #646
Rename `number_of_column` in the `Row` class to `number_of_columns`. This fixes a typo.
> feat: rename `number_of_column` in `Row` to `number_of_columns`

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_group_rows.py
Closes #611
Rename `group_rows_by` in the `Table` class to `group_rows`. This is more in line with similar methods that expect a callback like `sort_rows` or `filter_rows`.
> feat: rename `group_rows_by` in `Table` to `group_rows`

- src/safeds/data/tabular/containers/_column.py
Closes partially #532
Closes #620
Remove all parameter & result types from docstrings in the `Column` class. This also fixes #620.
> docs: remove types from docstrings in `Column`

- src/safeds/ml/classical/classification/_support_vector_machine.py
- src/safeds/ml/classical/regression/_support_vector_machine.py
- tests/safeds/ml/classical/classification/test_support_vector_machine.py
- tests/safeds/ml/classical/regression/test_support_vector_machine.py
Closes #602
Previously, support vector machines always used an RBF kernel, regardless of the `kernel` requested by the user. This is fixed now.
> fix: actually use `kernel` of support vector machines for training

- src/safeds/data/tabular/containers/_column.py
- tests/safeds/data/tabular/containers/_column/test_missing_value_count.py
Closes #642
Add `Column.missing_value_count` to get the absolute number of missing values in the column.
> feat: add `Column.missing_value_count`

- src/safeds/data/tabular/containers/_row.py
- tests/safeds/data/tabular/containers/test_row.py
Closes #584
`Row.sort_columns` now takes four parameters `name1`, `value1`, `name2`, `value2` instead of two tuples of shape `(name1, value1)`, `(name2, value2)`.
> feat: callback `Row.sort_columns` takes four parameters instead of two tuples

- src/safeds/exceptions/__init__.py
- src/safeds/exceptions/_ml.py
- src/safeds/ml/classical/_util_sklearn.py
- src/safeds/ml/classical/classification/_ada_boost.py
- src/safeds/ml/classical/classification/_classifier.py
- src/safeds/ml/classical/classification/_decision_tree.py
- src/safeds/ml/classical/classification/_gradient_boosting.py
- src/safeds/ml/classical/classification/_k_nearest_neighbors.py
- src/safeds/ml/classical/classification/_logistic_regression.py
- src/safeds/ml/classical/classification/_random_forest.py
- src/safeds/ml/classical/classification/_support_vector_machine.py
- src/safeds/ml/classical/regression/_ada_boost.py
- src/safeds/ml/classical/regression/_decision_tree.py
- src/safeds/ml/classical/regression/_elastic_net_regression.py
- src/safeds/ml/classical/regression/_gradient_boosting.py
- src/safeds/ml/classical/regression/_k_nearest_neighbors.py
- src/safeds/ml/classical/regression/_lasso_regression.py
- src/safeds/ml/classical/regression/_linear_regression.py
- src/safeds/ml/classical/regression/_random_forest.py
- src/safeds/ml/classical/regression/_regressor.py
- src/safeds/ml/classical/regression/_ridge_regression.py
- src/safeds/ml/classical/regression/_support_vector_machine.py
- tests/safeds/ml/classical/classification/test_classifier.py
- tests/safeds/ml/classical/regression/test_regressor.py
Closes #636
No longer raise an error if a table that already contains the target is passed to `predict`. It's now simply ignored for training and overwritten.
> feat: allow using tables that already contain target for prediction

- mkdocs.yml
Hide dunder methods in API documentation to reduce clutter.
> docs: hide dunder methods

- src/safeds/ml/nn/__init__.py
- src/safeds/ml/nn/_forward_layer.py
- src/safeds/ml/nn/_input_conversion.py
- src/safeds/ml/nn/_input_conversion_table.py
- src/safeds/ml/nn/_layer.py
- src/safeds/ml/nn/_model.py
- src/safeds/ml/nn/_output_conversion.py
- src/safeds/ml/nn/_output_conversion_table.py
Closes #690
Closes #691
* Make `_Layer` public (now called `Layer`)
* Make `_InputConversion` public (now called `InputConversion`)
* Make `_OutputConversion` public (now called `OutputConversion`)
> fix: make `_Layer`, `_InputConversion`, `_OutputConversion` public

- src/safeds/data/tabular/containers/_column.py
- tests/safeds/data/tabular/containers/_column/test_to_table.py
Closes #695
Add method `Column.to_table` to get a `Table` from a `Column`.
> feat: add `Column.to_table`

- .github/workflows/main.yml
- .github/workflows/pr.yml
Disable the MacOS tests again, since PyTorch cannot be installed on them. Long term, we should activate these tests and only upgrade once they pass.
> ci: disable MacOS again

- poetry.lock
- pyproject.toml
* For MacOS, get `torch` from PyPI. This fixes an installation error.
* For Linux, get `torch` from PyPI. It already includes CUDA support.
* For Windows, get `torch` from `https://download.pytorch.org/whl/cu121`, but only as a dev dependency. Anyone using the library, always gets the default `torch` version without CUDA from PyPI, unless they explicitly change that. The source defined in `pyproject.toml` is completely ignored.
> build: get `torch` from PyPI except as dev dependency on Windows

- src/safeds/data/tabular/containers/_column.py
- tests/safeds/data/tabular/containers/_column/test_summarize_statistics.py
Closes #701
Added `summarize_statistics` to the `Column` class to quickly get an overview of relevant statistics.
The Column is converted into a Table with one Column and the results from Table.summarize_statistics() are returned. This way, if someone adds a new feature to Table.summarize_statistics(), it also appears in Column.summarize_statistics().
> feat: added Column.summarize_statistics()

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_remove_rows.py
Closes #698
Add a method `Table.remove_rows`. It's the same as `Table.filter_rows` with a negated query.
> feat: `Table.remove_rows`

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_keep_only_rows.py
* New method `Table.keep_only_rows`. This is consistent with `Table.keep_only_columns`.
* Deprecate `Table.filter_rows`, which does the same thing. It will be removed in a future version.
> feat: `Table.keep_only_rows`

- .github/README.md
- docs/README.md
- src/safeds/data/tabular/containers/_table.py
Closes #722
* Deprecate `Table.add_column` in favor of `Table.add_columns`.
* Deprecate `Table.add_row` in favor of `Table.add_rows`.
> feat: deprecate `Table.add_column` and `Table.add_row`

- src/safeds/data/tabular/transformation/_imputer.py
- src/safeds/data/tabular/transformation/_label_encoder.py
- src/safeds/data/tabular/transformation/_one_hot_encoder.py
- src/safeds/data/tabular/transformation/_table_transformer.py
- tests/safeds/data/tabular/transformation/test_discretizer.py
- tests/safeds/data/tabular/transformation/test_imputer.py
- tests/safeds/data/tabular/transformation/test_label_encoder.py
- tests/safeds/data/tabular/transformation/test_one_hot_encoder.py
- tests/safeds/data/tabular/transformation/test_range_scaler.py
- tests/safeds/data/tabular/transformation/test_standard_scaler.py
- tests/safeds/data/tabular/transformation/test_table_transformer.py
Closes #613
`TableTransformer.fit_and_transform` now returns a tuple containing
* the fitted transformer
* the transformed table.
> feat: return fitted transformer and transformed table from `fit_and_transform`

- src/safeds/data/image/containers/_empty_image_list.py
- src/safeds/data/image/containers/_image_list.py
- src/safeds/data/image/containers/_multi_size_image_list.py
- src/safeds/data/image/containers/_single_size_image_list.py
- tests/safeds/data/image/containers/test_image_list.py
Closes #626
`Image.clone` is now internal. It should never be called explicitly by users, since our implementation already takes care of ensuring immutability.
> fix: make `Image.clone` internal

- src/safeds/data/tabular/containers/_table.py
Closes #727
* Deprecate `Table.from_excel_file`.
* Deprecate `Table.to_excel_file`.
> feat: deprecated `Table.from_excel_file` and `Table.to_excel_file`

- src/safeds/ml/classical/classification/_classifier.py
- src/safeds/ml/classical/regression/_regressor.py
- tests/safeds/ml/classical/classification/test_classifier.py
- tests/safeds/ml/classical/regression/test_regressor.py
Closes #713
Add `Regressor.summarize_metrics` and `Classifier.summarize_metrics` to quickly check suitable metrics.
> feat: `Regressor.summarize_metrics` and `Classifier.summarize_metrics`

- src/safeds/ml/classical/classification/_decision_tree.py
- src/safeds/ml/classical/classification/_random_forest.py
- src/safeds/ml/classical/regression/_decision_tree.py
- src/safeds/ml/classical/regression/_random_forest.py
- tests/safeds/ml/classical/classification/test_decision_tree.py
- tests/safeds/ml/classical/regression/test_decision_tree.py
Closes #700
Add regularization options for decision trees and random forests:
* maximum depth
* minimum number of samples in leaves
> feat: regularization for decision trees and random forests

- src/safeds/data/tabular/containers/_experimental_polars_row.py
- src/safeds/data/tabular/containers/_experimental_polars_table.py
- src/safeds/data/tabular/containers/_experimental_vectorized_cell.py
- src/safeds/data/tabular/containers/_experimental_vectorized_row.py
Closes partially #712
Add an implementation of a row based on a polars-backed **Table**. This allows us to keep using callbacks for filters etc., and still have vectorized operations.
> feat: polars implementation of a row

- src/safeds/data/tabular/containers/_column.py
- tests/safeds/data/tabular/containers/_column/test_stability.py
- tests/safeds/data/tabular/containers/_column/test_summarize_statistics.py
* `False` (or any falsy non-numeric value) was replaced by `-` in `summarize_statistics` for min/max. It's now displayed properly.
* `stability` could not be computed for boolean columns (polars ComputeError). This is fixed.
> fix: handling of boolean columns in column statistics

- src/safeds/_validation/_check_columns_are_numeric.py
- src/safeds/data/tabular/containers/_column.py
- src/safeds/data/tabular/containers/_row.py
- src/safeds/data/tabular/containers/_table.py
- src/safeds/data/tabular/plotting/_column_plotter.py
- tests/safeds/data/tabular/containers/_column/test_correlation_with.py
- tests/safeds/data/tabular/containers/_column/test_mean.py
- tests/safeds/data/tabular/containers/_column/test_median.py
- tests/safeds/data/tabular/containers/_column/test_plot_box_plot.py
- tests/safeds/data/tabular/containers/_column/test_plot_lag_plot.py
- tests/safeds/data/tabular/containers/_column/test_standard_deviation.py
- tests/safeds/data/tabular/containers/_column/test_variance.py
- tests/safeds/data/tabular/containers/_table/test_count_row_if.py
Closes #786 
Add a new method `Table.count_row_if` to count the rows in a table that satisfy a given predicate.
> feat: `Table.count_row_if`

- docs/tutorials/classification.ipynb
- docs/tutorials/data_processing.ipynb
- src/safeds/data/labeled/containers/_image_dataset.py
- src/safeds/data/tabular/containers/_table.py
- src/safeds/data/tabular/transformation/_discretizer.py
- src/safeds/data/tabular/transformation/_label_encoder.py
- src/safeds/data/tabular/transformation/_one_hot_encoder.py
- src/safeds/data/tabular/transformation/_range_scaler.py
- src/safeds/data/tabular/transformation/_simple_imputer.py
- src/safeds/data/tabular/transformation/_standard_scaler.py
- src/safeds/data/tabular/transformation/_table_transformer.py
- src/safeds/ml/nn/_model.py
- tests/safeds/data/labeled/containers/test_image_dataset.py
- tests/safeds/data/tabular/containers/_table/test_inverse_transform_table.py
- tests/safeds/data/tabular/containers/_table/test_transform_table.py
- tests/safeds/data/tabular/transformation/test_discretizer.py
- tests/safeds/data/tabular/transformation/test_label_encoder.py
- tests/safeds/data/tabular/transformation/test_one_hot_encoder.py
- tests/safeds/data/tabular/transformation/test_range_scaler.py
- tests/safeds/data/tabular/transformation/test_simple_imputer.py
- tests/safeds/data/tabular/transformation/test_standard_scaler.py
- tests/safeds/data/tabular/transformation/test_table_transformer.py
- tests/safeds/ml/nn/test_cnn_workflow.py
- tests/safeds/ml/nn/test_forward_workflow.py
- tests/safeds/ml/nn/test_lstm_workflow.py
Specify the names of the columns that a table transformer should be applied to in its constructor instead of its `fit` method. This allows easier composition.
> feat: specify column names in constructor of table transformers

- docs/tutorials/classification.ipynb
- docs/tutorials/convolutional_neural_network_for_image_classification.ipynb
- docs/tutorials/machine_learning.ipynb
- src/safeds/data/labeled/containers/_tabular_dataset.py
- src/safeds/data/tabular/transformation/__init__.py
- src/safeds/data/tabular/transformation/_discretizer.py
- src/safeds/data/tabular/transformation/_invertible_table_transformer.py
- src/safeds/data/tabular/transformation/_label_encoder.py
- src/safeds/data/tabular/transformation/_one_hot_encoder.py
- src/safeds/data/tabular/transformation/_range_scaler.py
- src/safeds/data/tabular/transformation/_simple_imputer.py
- src/safeds/data/tabular/transformation/_standard_scaler.py
- src/safeds/ml/nn/_internal_model.py
- src/safeds/ml/nn/_model.py
- src/safeds/ml/nn/layers/_convolutional2d_layer.py
- src/safeds/ml/nn/layers/_flatten_layer.py
- src/safeds/ml/nn/layers/_forward_layer.py
- src/safeds/ml/nn/layers/_internal_layers.py
- src/safeds/ml/nn/layers/_lstm_layer.py
- src/safeds/ml/nn/layers/_pooling2d_layer.py
- tests/safeds/ml/nn/converters/test_input_converter_time_series.py
- tests/safeds/ml/nn/layers/test_forward_layer.py
- tests/safeds/ml/nn/layers/test_lstm_layer.py
- tests/safeds/ml/nn/test_forward_workflow.py
- tests/safeds/ml/nn/test_lstm_workflow.py
- tests/safeds/ml/nn/test_model.py
* Users no longer need to specify input sizes of forward and LSTM layers.
* The constructor parameter `output_size` of these two layers has been renamed to `neuron_count`.
> feat: infer input size of forward and LSTM layers

- .github/workflows/main.yml
- .github/workflows/pr.yml
Don't run tests on Windows/MacOS and Python 3.11 to not overload the cache.
> ci: exclude two matrix configurations

- poetry.lock
build(deps): Bump `pytorch` from 2.3.0 to 2.3.1
build(deps): Bump `torchvision` from 0.18.0 to 0.18.1
> build(deps): Bump `pytorch` to 2.3.1 and `torchvision` to 0.18.1

- docs/tutorials/data_processing.ipynb
- src/safeds/data/tabular/transformation/_range_scaler.py
Closes #809 
- reorders parameters of RangeScaler and makes them keyword-only
- updates a Tutorial in the Documentation
> feat: reorders parameters of RangeScaler and makes them keyword-only

- src/safeds/data/tabular/transformation/__init__.py
- src/safeds/data/tabular/transformation/_robust_scaler.py
- tests/safeds/data/tabular/transformation/test_robust_scaler.py
Closes #650 
Adds a RobustScaler class that works like the StandardScaler but uses median instead of mean and interquartile range instead of standard deviation. If the interquartile range is 0 it will only substract the median from all rows.
For now cannot handle columns containing NaN-values. See Issue #873
> feat: add robustscaler

- docs/tutorials/classification.ipynb
Closes #686 
0. Improved text 
1. removed columns `name`, `id`, `ticket`,  `parents_children`, `cabin` completely
2. OneHot encoded `sex` and `port_embarked` 
3. SimpleImpute `age` and  `fare`
4. reverse transformed OneHot encoding
> docs: add more data processing steps to the classification tutorial

- docs/tutorials/regression.ipynb
- src/safeds/data/tabular/transformation/__init__.py
- src/safeds/data/tabular/transformation/_functional_table_transformer.py
- tests/safeds/data/tabular/transformation/test_functional_table_transformer.py
- tests/safeds/data/tabular/transformation/test_table_transformer.py
Closes #858 
This implements a Transformer that wraps a Callable[[Table], Table] so operations on Tables can be inserted into the operation order of a SequentialTableTransformer.
Note that this transformer inherently cannot be invertible.
Since there is no type checking at runtime, callables with wrong argument or return types will only throw an exception upon calling transform but not during init.
> feat: add FunctionalTableTransformer

- tests/safeds/data/tabular/transformation/test_table_transformer.py
Closes #902
Test coverage for RobustScaler.\_\_ hash\_\_() by adding RobustScaler to the list of Numeric Table Transformers in test_table_transformer.py
> test: Added RobustScaler to test_table_transformer.py

- src/safeds/data/tabular/containers/_cell.py
- tests/safeds/data/tabular/containers/_cell/test_first_not_none.py
Closes #799 
Added static method to Cell, which returns a Cell containing the polars expression of the first Cell in the list that is not None.
Works on a list of Cells, regardless of Cell type (numeric, string, date, etc.).
Returns None if given an empty list.
> feat: get first cell with value other than `None`

- src/safeds/data/tabular/containers/_cell.py
- src/safeds/data/tabular/containers/_lazy_cell.py
- tests/safeds/data/tabular/containers/_cell/test_add.py
- tests/safeds/data/tabular/containers/_cell/test_and.py
- tests/safeds/data/tabular/containers/_cell/test_div.py
- tests/safeds/data/tabular/containers/_cell/test_eq.py
- tests/safeds/data/tabular/containers/_cell/test_floordiv.py
- tests/safeds/data/tabular/containers/_cell/test_ge.py
- tests/safeds/data/tabular/containers/_cell/test_gt.py
- tests/safeds/data/tabular/containers/_cell/test_le.py
- tests/safeds/data/tabular/containers/_cell/test_lt.py
- tests/safeds/data/tabular/containers/_cell/test_mod.py
- tests/safeds/data/tabular/containers/_cell/test_mul.py
- tests/safeds/data/tabular/containers/_cell/test_ne.py
- tests/safeds/data/tabular/containers/_cell/test_or.py
- tests/safeds/data/tabular/containers/_cell/test_pow.py
- tests/safeds/data/tabular/containers/_cell/test_sub.py
- tests/safeds/data/tabular/containers/_cell/test_xor.py
Always unwrap the right operators of cell operations. This was missing in some cases, leading to runtime errors akin to 
```cannot create expression literal for value of type _LazyCell: <Expr ['[(col("Shortness of breath on …'] at 0x18E78C3E010>```
> fix: unwrap operators of cell operations

- benchmarks/table/row_operations.py
- docs/development/guidelines/documentation.md
- docs/tutorials/data_processing.ipynb
- src/safeds/data/tabular/containers/_lazy_vectorized_row.py
- src/safeds/data/tabular/containers/_row.py
- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_row/test_get_cell.py
- tests/safeds/data/tabular/containers/_table/test_remove_rows.py
Rename `Row.get_value` to `Row.get_cell` to avoid confusion with `Column.get_value`. The row method returns a cell, while the column method returns an actual Python constant. The new name emphasizes this difference.
> feat: rename `Row.get_value` to `Row.get_cell`

- src/safeds/data/tabular/containers/_table.py
- src/safeds/data/tabular/typing/_polars_schema.py
Avoid a potential `PerformanceWarning` raised by `polars` when accessing `Table.column_count`.
> fix: avoid performance warning when accessing `column_count`

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_count_rows_if.py
Rename `Table.count_row_if` to `Table.count_rows_if` (plural). 
For all other methods of `Table`, the plural form was used, but if users typed "rows", this method was not suggested by auto-completion. The `_if` suffix is still included, to distinguish the method from the attribute `row_count`.
> feat: rename `count_row_if` to `count_rows_if`

- docs/tutorials/convolutional_neural_network_for_image_classification.ipynb
- docs/tutorials/time_series_forecasting.ipynb
- src/safeds/ml/nn/_model.py
- tests/safeds/ml/nn/test_cnn_workflow.py
- tests/safeds/ml/nn/test_dropout_workflow.py
- tests/safeds/ml/nn/test_forward_workflow.py
- tests/safeds/ml/nn/test_lstm_workflow.py
- tests/safeds/ml/nn/test_model.py
In `fit` methods of `NeuralNetworkRegressor` and `NeuralNetworkClassifier`, rename the parameter `epoch_size` to `epoch_count. 
The previous name did not match, since an epoch has no size.
> feat: rename `epoch_size` to `epoch_count`

- src/safeds/data/tabular/containers/_table.py
- src/safeds/data/tabular/plotting/_table_plotter.py
- src/safeds/data/tabular/transformation/_label_encoder.py
- tests/safeds/data/image/containers/test_image.py
- tests/safeds/data/tabular/containers/_row/test_column_count.py
- tests/safeds/data/tabular/containers/_row/test_column_names.py
- tests/safeds/data/tabular/containers/_row/test_contains.py
- tests/safeds/data/tabular/containers/_row/test_eq.py
- tests/safeds/data/tabular/containers/_row/test_get_column_type.py
- tests/safeds/data/tabular/containers/_row/test_getitem.py
- tests/safeds/data/tabular/containers/_row/test_has_column.py
- tests/safeds/data/tabular/containers/_row/test_hash.py
- tests/safeds/data/tabular/containers/_row/test_iter.py
- tests/safeds/data/tabular/containers/_row/test_len.py
- tests/safeds/data/tabular/containers/_row/test_schema.py
- tests/safeds/data/tabular/containers/_row/test_sizeof.py
- tests/safeds/data/tabular/containers/_table/test_join.py
Migrate our code, so it no longer uses deprecated API elements of third-party libraries.
> fix: handle deprecations in third-party libraries

- src/safeds/data/tabular/containers/_table.py
- tests/safeds/data/tabular/containers/_table/test_filter_rows.py
- tests/safeds/data/tabular/containers/_table/test_filter_rows_by_column.py
- tests/safeds/data/tabular/containers/_table/test_remove_rows.py
- tests/safeds/data/tabular/containers/_table/test_remove_rows_by_column.py
Closes #998
`Table.removeRows` and `Table.removeRowsByColumn` now keep missing values, i.e. they only remove rows for which the predicate returns `True`.
> fix: handling of missing value in `removeRows`/`removeRowsByColumn`
