.github/workflows/issue.yml
Update workflow to add new issues to the correct project.
=> ci: add issues to correct project

docs/assets/logo.svg, mkdocs.yml
Add a custom logo and favicon to the documentation.
=> docs: configure logo and favicon

src/pyproject.toml
Closes #5 .
* Bump version number
* Improve description
* Add link to README
* Add link to repo
* Add link to docs
* Add keywords
=> build: add metadata to pyproject.toml

.github/workflows/release.yml
Give `GITHUB_TOKEN` write permission.
=> ci: release permissions

package-lock.json, package.json, release.config.js
Configure `semantic-release` in this repo instead of using a shared configuration.
=> ci: include configuration of semantic release in repo

.github/workflows/release.yml, package-lock.json, package.json, release.config.js
Since we use required workflows, nobody can currently push to main. See this discussion: https://github.com/orgs/community/discussions/43890
=> ci: when releasing, create a PR instead of pushing to main

docs/development/guidelines.md, mkdocs.yml
Closes #16.
Add development guidelines to documentation. The original issue is no longer needed.
=> docs: add development guidelines

docs/development/environment.md, docs/tutorials/data_visualization.md, mkdocs.yml
Add documentation how to set up a dev environment, run the tests, and build the documentation.
=> docs: describe how to set up a dev environment

mkdocs.yml
* Add changelog to navigation of documentation
=> docs: link to changelog

mkdocs.yml
* Show "Back to Top" button
* Allow to attach documents to section headers (good for overview pages)
=> docs: better navigation

.github/workflows/dependency-review.yml, .github/workflows/megalinter.yml, .github/workflows/release.yml, package-lock.json, package.json, release.config.js
Instead of creating a pull request with the files changed by a release, push to main again.
=> ci: push changelog and files with updated versions on release

src/safeds/ml/classification/__init__.py, src/safeds/ml/classification/_ada_boost.py, src/safeds/ml/classification/_classifier.py, src/safeds/ml/classification/_decision_tree.py, src/safeds/ml/classification/_gradient_boosting_classification.py, src/safeds/ml/classification/_k_nearest_neighbors.py, src/safeds/ml/classification/_logistic_regression.py, src/safeds/ml/classification/_random_forest.py, src/safeds/ml/regression/__init__.py, src/safeds/ml/regression/_ada_boost.py, src/safeds/ml/regression/_decision_tree.py, src/safeds/ml/regression/_elastic_net_regression.py, src/safeds/ml/regression/_gradient_boosting_regression.py, src/safeds/ml/regression/_k_nearest_neighbors.py, src/safeds/ml/regression/_lasso_regression.py, src/safeds/ml/regression/_linear_regression.py, src/safeds/ml/regression/_random_forest.py, src/safeds/ml/regression/_regressor.py, src/safeds/ml/regression/_ridge_regression.py
Closes #60.
* Create abstract base class `Classifier` and make all current classifiers subclasses of it
* Create abstract base class `Regressor` and make all current regressors subclasses of it.
=> refactor: create abstract base classes `Classifier` and `Regressor` for supervised models

src/safeds/data/tabular/containers/__init__.py, src/safeds/data/tabular/containers/_column.py, src/safeds/data/tabular/containers/_table.py, src/safeds/data/tabular/transformation/_imputer.py, tests/safeds/data/tabular/containers/_column/test_idness.py, tests/safeds/data/tabular/containers/_column/test_maximum.py, tests/safeds/data/tabular/containers/_column/test_mean.py, tests/safeds/data/tabular/containers/_column/test_median.py, tests/safeds/data/tabular/containers/_column/test_minimum.py, tests/safeds/data/tabular/containers/_column/test_mode.py, tests/safeds/data/tabular/containers/_column/test_stability.py, tests/safeds/data/tabular/containers/_column/test_sum.py, tests/safeds/data/tabular/containers/_table/test_summary.py, tests/safeds/data/tabular/transformation/_imputer/test_imputer.py, tests/safeds/data/tabular/transformation/_one_hot_encoder/test_fit_transform.py
Closes #65.
* Renamed `min` to `minimum` and `max` to `maximum`
* Move statistics methods into the `Column` class
* Remove `ColumnStatistics` class
=> refactor: integrate statistics methods directly into `Column`

src/safeds/ml/classification/_ada_boost.py, src/safeds/ml/classification/_classifier.py, src/safeds/ml/classification/_decision_tree.py, src/safeds/ml/classification/_gradient_boosting_classification.py, src/safeds/ml/classification/_k_nearest_neighbors.py, src/safeds/ml/classification/_logistic_regression.py, src/safeds/ml/classification/_random_forest.py, src/safeds/ml/regression/_ada_boost.py, src/safeds/ml/regression/_decision_tree.py, src/safeds/ml/regression/_elastic_net_regression.py, src/safeds/ml/regression/_gradient_boosting_regression.py, src/safeds/ml/regression/_k_nearest_neighbors.py, src/safeds/ml/regression/_lasso_regression.py, src/safeds/ml/regression/_linear_regression.py, src/safeds/ml/regression/_random_forest.py, src/safeds/ml/regression/_regressor.py, src/safeds/ml/regression/_ridge_regression.py
Rename `tagged_table` parameter of `fit` to `training_set` to match standard terminology.
=> feat: rename `tagged_table` parameter of `fit` to `training_set`

src/safeds/data/tabular/containers/_column.py, src/safeds/data/tabular/containers/_row.py, src/safeds/data/tabular/containers/_table.py
Closes #80.
Improve the docstrings of the `Column`, `Row`, and `Table` classes.
=> docs: improve docstrings of `Column`, `Row`, and `Table`

src/safeds/data/tabular/containers/_table.py, src/safeds/data/tabular/transformation/_imputer.py, tests/safeds/data/tabular/containers/_table/test_drop_columns_with_non_numerical_values.py
Closes #13.
Add a method `drop_columns_with_non_numerical_values` to the `Table` class to return a new table without columns with non-numerical values.
=> feat: function to drop columns with non-numerical values from `Table`

src/safeds/ml/classification/_ada_boost.py, src/safeds/ml/classification/_classifier.py, src/safeds/ml/classification/_decision_tree.py, src/safeds/ml/classification/_gradient_boosting_classification.py, src/safeds/ml/classification/_k_nearest_neighbors.py, src/safeds/ml/classification/_logistic_regression.py, src/safeds/ml/classification/_random_forest.py, src/safeds/ml/regression/_ada_boost.py, src/safeds/ml/regression/_decision_tree.py, src/safeds/ml/regression/_elastic_net_regression.py, src/safeds/ml/regression/_gradient_boosting_regression.py, src/safeds/ml/regression/_k_nearest_neighbors.py, src/safeds/ml/regression/_lasso_regression.py, src/safeds/ml/regression/_linear_regression.py, src/safeds/ml/regression/_random_forest.py, src/safeds/ml/regression/_regressor.py, src/safeds/ml/regression/_ridge_regression.py, tests/safeds/ml/classification/test_classifier.py, tests/safeds/ml/regression/test_regressor.py
Add a new method `is_fitted` to `Classifier`s and `Regressor`s to easily check whether they have been fitted already.
=> feat: new method `is_fitted` to check whether a model is fitted

src/safeds/data/tabular/containers/_column.py, src/safeds/data/tabular/typing/__init__.py, src/safeds/data/tabular/typing/_column_type.py, src/safeds/data/tabular/typing/_table_schema.py, tests/safeds/data/tabular/containers/_row/test_count.py, tests/safeds/data/tabular/containers/_row/test_get_column_names.py, tests/safeds/data/tabular/containers/_row/test_iter.py, tests/safeds/data/tabular/containers/_row/test_len.py, tests/safeds/data/tabular/containers/_table/test_add_column.py, tests/safeds/data/tabular/containers/_table/test_add_columns.py, tests/safeds/data/tabular/containers/_table/test_add_row.py, tests/safeds/data/tabular/containers/_table/test_remove_columns_with_missing_values.py, tests/safeds/data/tabular/containers/_table/test_remove_columns_with_non_numerical_values.py, tests/safeds/data/tabular/containers/_table/test_remove_rows_with_missing_values.py, tests/safeds/data/tabular/containers/_table/test_remove_rows_with_outliers.py, tests/safeds/data/tabular/containers/_table/test_table.py, tests/safeds/data/tabular/containers/_table/test_to_rows.py, tests/safeds/data/tabular/typing/_table_schema/test__str__.py, tests/safeds/data/tabular/typing/_table_schema/test_get_column_type.py, tests/safeds/data/tabular/typing/_table_schema/test_table_equals.py, tests/safeds/data/tabular/typing/test_column_type.py
Closes #113.
* Rename subclasses:
| old| new |
|--------|--------|
| IntColumnType | Integer |
| BooleanColumnType | Boolean |
| FloatColumnType | RealNumber |
| StringColumnType | String |
* Add new subclass `Anything` for columns that contain any values
* Add parameter `is_nullable` to all types to indicate that null values are allowed
* Add tests
=> feat: improve `ColumnType`s

src/safeds/ml/classification/_k_nearest_neighbors.py, src/safeds/ml/regression/_k_nearest_neighbors.py
Rename the `n_neighbors` parameter of `KNearestNeighbors` to `number_of_neighbors` for the sake of consistency.
=> feat: rename `n_neighbors` to `number_of_neighbors`

src/safeds/data/tabular/containers/_table.py, src/safeds/data/tabular/typing/_schema.py
Closes #180.
* Change `pd.Dataframe` to `pd.DataFrame`
=> fix: typo in type hint

src/safeds/data/tabular/containers/_row.py, src/safeds/data/tabular/containers/_table.py, tests/safeds/data/tabular/containers/_table/test_add_row.py, tests/safeds/data/tabular/containers/_table/test_add_rows.py, tests/safeds/data/tabular/containers/_table/test_to_rows.py, tests/safeds/data/tabular/containers/test_row.py
* Make `Row` a subclass of `Mapping`
* Give `Row` a usable constructor
* Rename `get_column_names` to `column_names` and make it a property
* Rename `count` to `n_columns` and make it a property
* Rename `get_type_of_column` to `get_column_type`
=> feat: clean up `Row` class

docs/development/guidelines.md
Closes #191.
Improve guidelines how to write good docstrings.
=> docs: better guidance on how to write docstrings

docs/README.md, docs/development/guidelines.md
* Link to the *latest* version of the resources for contributors from the `README`
=> docs: easier access to resources for contributors

docs/development/guidelines.md
Closes #273.
Explain how parameters should be ordered.
=> docs: guideline about parameter order

src/safeds/data/image/containers/_image.py, src/safeds/data/tabular/containers/_column.py, src/safeds/data/tabular/containers/_row.py, src/safeds/data/tabular/containers/_table.py, src/safeds/data/tabular/containers/_tagged_table.py
Closes #346
Updated the docstrings of methods in `src/safeds/data` to state that copies are returned, with the original object left unmodified.
=> docs: Improve wording on stating that a method does not work in-place

src/safeds/data/image/containers/_image.py
Removed method comment and added Issue #525
=> docs: Removed comment for adjust_color_balance method in Image

poetry.lock, pyproject.toml
Remove dependency `ipython` since we no longer use it.
=> build(deps): remove `ipython`

docs/README.md
Closes #718
Document when and how to install the CUDA versions of torch.
=> docs: install CUDA versions of torch

docs/development/environment.md
Closes #781
Update the link to the poetry installer.
=> docs: fix broken link to poetry installer

src/safeds/data/tabular/containers/_column.py, src/safeds/ml/nn/converters/_input_converter_table.py, src/safeds/ml/nn/converters/_input_converter_time_series.py
Add some missing parameter descriptions to docstrings.
=> docs: add some missing descriptions for parameters

docs/tutorials/regression.ipynb
Closes #804 
- Fixes Relative-Link Bug in Regression-Tutorial
=> docs: fix broken link in regression tutorial

src/safeds/data/labeled/containers/_time_series_dataset.py, src/safeds/data/tabular/plotting/_table_plotter.py
Closes #XYZ
changed some docs in time series dataset and moving average plot.
=> docs: fixed docs

src/safeds/ml/nn/_model.py
Rename methods to create NNs from pretrained models to `from_pretrained_model` to fit the pattern of other static factory methods.
=> feat: rename `load_pretrained_model` to `from_pretrained_model`
